name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up SSH
        shell: powershell
        run: |
          $sshDir = "$HOME\.ssh"
          if (!(Test-Path -Path $sshDir)) {
            New-Item -ItemType Directory -Path $sshDir | Out-Null
          }
          Set-Content -Path "$sshDir\id_ed25519" -Value "${{ secrets.SSH_PRIVATE_KEY }}"
          icacls "$sshDir\id_ed25519" /inheritance:r
          icacls "$sshDir\id_ed25519" /grant:r "$($env:USERNAME):(R)"
          ssh-keyscan github.com | Out-File -Append -FilePath "$sshDir\known_hosts"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: omiete01/githubaction:latest
